In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#Transaction

In [2]:
transaction_dataset = 'https://raw.githubusercontent.com/MIlhamEr/Data-Analytics-RQKB/main/QVI_transaction_data.xlsx'
transaction = pd.read_excel(transaction_dataset)

In [3]:
transaction.head()

,DATE,STORE_NBR,LYLTY_CARD_NBR,TXN_ID,PROD_NBR,PROD_NAME,PROD_QTY,TOT_SALES
0,43390,1,1000,1,5,Natural Chip Compny SeaSalt175g,2,6.0
1,43599,1,1307,348,66,CCs Nacho Cheese 175g,3,6.3
2,43605,1,1343,383,61,Smiths Crinkle Cut Chips Chicken 170g,2,2.9
3,43329,2,2373,974,69,Smiths Chip Thinly S/Cream&Onion 175g,5,15.0
4,43330,2,2426,1038,108,Kettle Tortilla ChpsHny&Jlpno Chili 150g,3,13.8

## Information
To do list:
1. Convert date format
2. Ensure PROD_NBR & PROD_NAME match
3. Describe PROD_QTY & TOT_SALES

In [4]:
transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264836 entries, 0 to 264835
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DATE            264836 non-null  int64
 1   STORE_NBR       264836 non-null  int64
 2   LYLTY_CARD_NBR  264836 non-null  int64
 3   TXN_ID          264836 non-null  int64
 4   PROD_NBR        264836 non-null  int64
 5   PROD_NAME       264836 non-null  object
 6   PROD_QTY        264836 non-null  int64
 7   TOT_SALES       264836 non-null  float64
dtypes: float64(1), int64(6), object(1)
memory usage: 16.2+ MB

## Date

In [5]:
transaction['DATE'] = pd.to_datetime(transaction['DATE'], errors='coerce', unit="D", origin = "1899-12-30")

In [6]:
print(transaction["DATE"].dt.year.value_counts())

DATE
2018    133691
2019    131145
Name: count, dtype: int64

In [7]:
print(transaction["DATE"].dt.month.value_counts())

DATE
12    22835
3     22592
7     22562
8     22411
5     22392
10    22288
1     22161
11    21852
6     21829
4     21766
9     21743
2     20405
Name: count, dtype: int64

## Statistic

In [8]:
transaction[['PROD_QTY', 'TOT_SALES']].describe()

            PROD_QTY      TOT_SALES
count  264836.000000  264836.000000
mean        1.907309       7.304200
std         0.643654       3.083226
min         1.000000       1.500000
25%         2.000000       5.400000
50%         2.000000       7.400000
75%         2.000000       9.200000
max       200.000000     650.000000

## Product Table

In [9]:
transaction[['PROD_NBR', 'PROD_NAME']].drop_duplicates().shape

(114, 2)

In [10]:
transaction['PROD_NBR'].nunique()

114

In [72]:
product = transaction[['PROD_NBR', 'PROD_NAME']].sort_values(by="PROD_NBR").drop_duplicates()

In [34]:
product

        PROD_NBR                                 PROD_NAME
85912          1   Smiths Crinkle Cut  Chips Barbecue 170g
8011           2    Cobs Popd Sour Crm  &Chives Chips 110g
7945           3  Kettle Sensations   Camembert & Fig 150g
117644         4          Dorito Corn Chp     Supreme 380g
7919           5    Natural Chip        Compny SeaSalt175g
...          ...                                       ...
8313         110            WW Original Corn    Chips 200g
26           111     Smiths Chip Thinly  Cut Original 175g
238094       112    Tyrrells Crisps     Ched & Chives 165g
238122       113                      Twisties Chicken270g
173077       114     Kettle Sensations   Siracha Lime 150g

[114 rows x 2 columns]

### Analyze The Product
Separate product name, brand, weight, flavor, and description

In [73]:
# Extracting first name from product name which is the brand name
product['BRAND_NAME']=product['PROD_NAME'].apply(lambda x: x.split(" ")[0])

In [74]:
# extracting the last word from product namewhich is the pkg details
product['PROD_PKG']=product['PROD_NAME'].apply(lambda x: x.split(" ")[-1])

In [75]:
# removing the first word from product name
product['PROD_DESC'] = product['PROD_NAME'].str.split(n=1).str[1]

In [76]:
# also removing the last word further to get the product description
product['PROD_DESC'] = product['PROD_DESC'].str.rsplit(' ', n=1).str[0]

In [77]:
product

,PROD_NBR,PROD_NAME,BRAND_NAME,PROD_PKG,PROD_DESC
85912,1,Smiths Crinkle Cut Chips Barbecue 170g,Smiths,170g,Crinkle Cut Chips Barbecue
8011,2,Cobs Popd Sour Crm &Chives Chips 110g,Cobs,110g,Popd Sour Crm &Chives Chips
7945,3,Kettle Sensations Camembert & Fig 150g,Kettle,150g,Sensations Camembert & Fig
117644,4,Dorito Corn Chp Supreme 380g,Dorito,380g,Corn Chp Supreme
7919,5,Natural Chip Compny SeaSalt175g,Natural,SeaSalt175g,Chip Compny
...,...,...,...,...,...
8313,110,WW Original Corn Chips 200g,WW,200g,Original Corn Chips
26,111,Smiths Chip Thinly Cut Original 175g,Smiths,175g,Chip Thinly Cut Original
238094,112,Tyrrells Crisps Ched & Chives 165g,Tyrrells,165g,Crisps Ched & Chives
238122,113,Twisties Chicken270g,Twisties,Chicken270g,Chicken270g
173077,114,Kettle Sensations Siracha Lime 150g,Kettle,150g,Sensations Siracha Lime

In [78]:
product.info()

<class 'pandas.core.frame.DataFrame'>
Index: 114 entries, 85912 to 173077
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   PROD_NBR    114 non-null    int64
 1   PROD_NAME   114 non-null    object
 2   BRAND_NAME  114 non-null    object
 3   PROD_PKG    114 non-null    object
 4   PROD_DESC   114 non-null    object
dtypes: int64(1), object(4)
memory usage: 5.3+ KB

In [79]:
product['PROD_DESC'] = product['PROD_DESC']+' '+ product['PROD_PKG'].str[:-4]

### Product Weight

In [80]:
print(product['PROD_PKG'].value_counts())

PROD_PKG
175g                  26
150g                  19
165g                   8
170g                   8
134g                   8
110g                   7
300g                   6
330g                   4
200g                   3
160g                   2
190g                   2
380g                   2
90g                    2
SeaSalt175g            1
210g                   1
270g                   1
70g                    1
Chli&S/Cream175G       1
150G                   1
210G                   1
125g                   1
Salt                   1
Ht300g                 1
250g                   1
CutSalt/Vinegr175g     1
180g                   1
220g                   1
Chs&Onion170g          1
Chckn175g              1
Chicken270g            1
Name: count, dtype: int64

In [81]:
#extracting only numeric characters
product['PROD_PKG']= product.PROD_PKG.str.extract('(\d+)')

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipython-input-2199973818.py:2: SyntaxWarning: invalid escape sequence '\d'
  product['PROD_PKG']= product.PROD_PKG.str.extract('(\d+)')

In [82]:
product.info()

<class 'pandas.core.frame.DataFrame'>
Index: 114 entries, 85912 to 173077
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   PROD_NBR    114 non-null    int64
 1   PROD_NAME   114 non-null    object
 2   BRAND_NAME  114 non-null    object
 3   PROD_PKG    113 non-null    object
 4   PROD_DESC   114 non-null    object
dtypes: int64(1), object(4)
memory usage: 5.3+ KB

1 PROD_PKG is missing

In [83]:
print(product.PROD_PKG.value_counts())

PROD_PKG
175    30
150    20
170     9
165     8
134     8
110     7
300     7
330     4
200     3
380     2
270     2
190     2
210     2
160     2
90      2
70      1
125     1
250     1
180     1
220     1
Name: count, dtype: int64

In [84]:
product["PROD_PKG"] = product["PROD_PKG"].fillna("No Value")

In [85]:
print(product["PROD_PKG"].value_counts())

PROD_PKG
175         30
150         20
170          9
134          8
165          8
300          7
110          7
330          4
200          3
380          2
190          2
210          2
270          2
160          2
90           2
70           1
125          1
No Value     1
250          1
180          1
220          1
Name: count, dtype: int64

In [86]:
product[product['PROD_PKG'] == 'No Value']

,PROD_NBR,PROD_NAME,BRAND_NAME,PROD_PKG,PROD_DESC
242457,63,Kettle 135g Swt Pot Sea Salt,Kettle,No Value,135g Swt Pot Sea

In [87]:
product["PROD_PKG"] = product["PROD_PKG"].replace({"No Value": "135"})

In [88]:
product[product['PROD_PKG'] == '135']

,PROD_NBR,PROD_NAME,BRAND_NAME,PROD_PKG,PROD_DESC
242457,63,Kettle 135g Swt Pot Sea Salt,Kettle,135,135g Swt Pot Sea

### Product Description

In [89]:
product.info()

<class 'pandas.core.frame.DataFrame'>
Index: 114 entries, 85912 to 173077
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   PROD_NBR    114 non-null    int64
 1   PROD_NAME   114 non-null    object
 2   BRAND_NAME  114 non-null    object
 3   PROD_PKG    114 non-null    object
 4   PROD_DESC   114 non-null    object
dtypes: int64(1), object(4)
memory usage: 5.3+ KB

In [90]:
print(product['PROD_DESC'].value_counts())

PROD_DESC
Original                         2
Popd Sour Crm  &Chives Chips     1
Sensations   Camembert & Fig     1
Corn Chp     Supreme             1
Chip        Compny SeaSalt       1
                                ..
Original Corn    Chips           1
Chip Thinly  Cut Original        1
Crisps     Ched & Chives         1
Chicken270g Chicken              1
Sensations   Siracha Lime        1
Name: count, Length: 113, dtype: int64

In [91]:
product.head()

,PROD_NBR,PROD_NAME,BRAND_NAME,PROD_PKG,PROD_DESC
85912,1,Smiths Crinkle Cut Chips Barbecue 170g,Smiths,170,Crinkle Cut Chips Barbecue
8011,2,Cobs Popd Sour Crm &Chives Chips 110g,Cobs,110,Popd Sour Crm &Chives Chips
7945,3,Kettle Sensations Camembert & Fig 150g,Kettle,150,Sensations Camembert & Fig
117644,4,Dorito Corn Chp Supreme 380g,Dorito,380,Corn Chp Supreme
7919,5,Natural Chip Compny SeaSalt175g,Natural,175,Chip Compny SeaSalt

# Purchase

In [26]:
purchase_dataset = "https://raw.githubusercontent.com/MIlhamEr/Data-Analytics-RQKB/4d25ff22b3128f6eb14f2fb60bb619f093c5f17a/QVI_purchase_behaviour.csv"
purchase = pd.read_csv(purchase_dataset)
purchase

       LYLTY_CARD_NBR               LIFESTAGE PREMIUM_CUSTOMER
0                1000   YOUNG SINGLES/COUPLES          Premium
1                1002   YOUNG SINGLES/COUPLES       Mainstream
2                1003          YOUNG FAMILIES           Budget
3                1004   OLDER SINGLES/COUPLES       Mainstream
4                1005  MIDAGE SINGLES/COUPLES       Mainstream
...               ...                     ...              ...
72632         2370651  MIDAGE SINGLES/COUPLES       Mainstream
72633         2370701          YOUNG FAMILIES       Mainstream
72634         2370751          YOUNG FAMILIES          Premium
72635         2370961          OLDER FAMILIES           Budget
72636         2373711   YOUNG SINGLES/COUPLES       Mainstream

[72637 rows x 3 columns]

In [27]:
purchase.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72637 entries, 0 to 72636
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   LYLTY_CARD_NBR    72637 non-null  int64
 1   LIFESTAGE         72637 non-null  object
 2   PREMIUM_CUSTOMER  72637 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.7+ MB

In [28]:
print(purchase.duplicated().sum())

0

In [29]:
print(purchase.isna().sum())

LYLTY_CARD_NBR      0
LIFESTAGE           0
PREMIUM_CUSTOMER    0
dtype: int64

In [30]:
print(purchase['LIFESTAGE'].value_counts())

LIFESTAGE
RETIREES                  14805
OLDER SINGLES/COUPLES     14609
YOUNG SINGLES/COUPLES     14441
OLDER FAMILIES             9780
YOUNG FAMILIES             9178
MIDAGE SINGLES/COUPLES     7275
NEW FAMILIES               2549
Name: count, dtype: int64

In [31]:
print(purchase['PREMIUM_CUSTOMER'].value_counts())

PREMIUM_CUSTOMER
Mainstream    29245
Budget        24470
Premium       18922
Name: count, dtype: int64